[versions]

dataforge = "0.10.3"
rsocket = "0.20.0"
xodus = "2.0.1"

uuid = "0.8.0"

jSerialComm = "2.11.4"

tornadofx = "1.7.20"

logback = "1.2.11"

hivemq = "1.3.12"

rabbitmq = "5.14.2"

exposed = "1.1.1"

kmongo = "4.5.1"

j2mod = "3.3.0"

milo = "1.1.1"

pi4j = "4.0.0"
#pi4j-ktx = "4.0.0"

plc4j = "0.13.1"

visionforge = "0.5.1"

kmath = "0.5.0"

testcontainers = "1.21.0"

[libraries]

dataforge-io = { module = "space.kscience:dataforge-io", version.ref = "dataforge" }
dataforge-meta = { module = "space.kscience:dataforge-meta", version.ref = "dataforge" }
tables-kt = { module = "space.kscience:tables-kt", version.ref = "dataforge" }

uuid = { module = "com.benasher44:uuid", version.ref = "uuid" }

xodus-entity-store = { module = "org.jetbrains.xodus:xodus-entity-store", version.ref = "xodus" }
xodus-environment = { module = "org.jetbrains.xodus:xodus-environment", version.ref = "xodus" }
xodus-vfs = { module = "org.jetbrains.xodus:xodus-vfs", version.ref = "xodus" }

rsocket-ktor-client = { module = "io.rsocket.kotlin:ktor-client-rsocket", version.ref = "rsocket" }
rsocket-ktor-server = { module = "io.rsocket.kotlin:ktor-server-rsocket", version.ref = "rsocket" }
rsocket-transport-ktor-tcp = { module = "io.rsocket.kotlin:rsocket-transport-ktor-tcp", version.ref = "rsocket" }

jSerialComm = { module = "com.fazecast:jSerialComm", version.ref = "jSerialComm" }

tornadofx = { module = "no.tornado:tornadofx", version.ref = "tornadofx" }

plotlykt-core = { module = "space.kscience:plotly-kt-core", version.ref = "visionforge" }

plotlykt-server = { module = "space.kscience:plotly-kt-server", version.ref = "visionforge" }

logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

hivemq-mqtt-client = { module = "com.hivemq:hivemq-mqtt-client", version.ref = "hivemq" }

rabbitmq-amqp-client = { module = "com.rabbitmq:amqp-client", version.ref = "rabbitmq" }

j2mod = { module = "com.ghgande:j2mod", version.ref = "j2mod" }

exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-kotlin-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }

h2 = "com.h2database:h2:2.3.232"

kmongo-coroutine-serialization = { module = "org.litote.kmongo:kmongo-coroutine-serialization", version.ref = "kmongo" }

milo-client = { module = "org.eclipse.milo:milo-sdk-client", version.ref = "milo" }
milo-sdk-core = { module = "org.eclipse.milo:milo-sdk-core", version.ref = "milo" }
milo-dtd-core = { module = "org.eclipse.milo:milo-dtd-core", version.ref = "milo" }
milo-server = { module = "org.eclipse.milo:milo-sdk-server", version.ref = "milo" }

#pi4j-ktx = { module = "com.pi4j:pi4j-ktx", version.ref = "pi4j-ktx" }
pi4j-core = { module = "com.pi4j:pi4j-core", version.ref = "pi4j" }
pi4j-plugin-raspberrypi = { module = "com.pi4j:pi4j-plugin-raspberrypi", version.ref = "pi4j" }
pi4j-plugin-pigpio = { module = "com.pi4j:pi4j-plugin-pigpio", version.ref = "pi4j" }

plc4j-spi = { module = "org.apache.plc4x:plc4j-spi", version.ref = "plc4j" }

visionforge-jupiter = { module = "space.kscience:visionforge-jupyter", version.ref = "visionforge" }
visionforge-markdown = { module = "space.kscience:visionforge-markdown", version.ref = "visionforge" }
visionforge-server = { module = "space.kscience:visionforge-server", version.ref = "visionforge" }
visionforge-compose-html = { module = "space.kscience:visionforge-compose-html", version.ref = "visionforge" }

sciprog-maps-compose = { module = "space.kscience:maps-kt-compose", version = "0.3.0" }

koala-plots = { module = "io.github.koalaplot:koalaplot-core", version = "0.9.0" }

kmath-core = { module = "space.kscience:kmath-core", version.ref = "kmath" }
kmath-stat = { module = "space.kscience:kmath-stat", version.ref = "kmath" }

testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-junit = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainers-hivemq = { module = "org.testcontainers:hivemq", version.ref = "testcontainers" }

# Buildscript

[plugins]

versions = "com.github.ben-manes.versions:0.51.0"
versions-update = "nl.littlerobots.version-catalog-update:0.8.4"
