package space.kscience.controls.proto.generation

import space.kscience.controls.spec.DeviceSpec

public data class CBackendOptions(
    val protoSources: List<ProtocolProtoSource> = listOf(ProtocolProtoSources.bundledDataForgeMeta()),
    val nanopbTextMaxLength: Int = 63,
) : ProtocolBackendOptions {
    init {
        require(nanopbTextMaxLength > 0) { "nanopb text max length must be positive" }
    }
}

public object CProtocolGenerator : ProtocolGenerator {
    override val language: ProtocolLanguage get() = ProtocolLanguage.C

    private const val METHOD_FIELD = "method"
    private const val GET_METHOD = "GET"
    private const val POST_METHOD = "POST"

    private data class CContext(
        val moduleName: String,
        val includeGuard: String,
        val headerName: String,
        val sourceName: String,
        val optionsName: String,
        val textMaxLength: Int,
        val properties: List<CPropertyInfo>,
    ) {
        val readableProperties: List<CPropertyInfo> get() = properties.filter { it.readable }
        val writableProperties: List<CPropertyInfo> get() = properties.filter { it.writable }
        val upperName: String get() = moduleName.uppercase()
    }

    private data class CPropertyInfo(
        val name: String,
        val cName: String,
        val enumSuffix: String,
        val type: ProtocolPropertyType,
        val readable: Boolean,
        val writable: Boolean,
        val rootStructName: String?,
    ) {
        val unionFieldName: String get() = cName
        val hasFlagName: String get() = "has_$cName"
        val validFlagName: String get() = "valid_$cName"
    }

    override fun generate(
        deviceSpec: DeviceSpec<*>,
        options: ProtocolGenerationOptions,
    ): GeneratedProtocolPackage {
        val backendOptions = options.cBackendOptions()
        val context = deviceSpec.cGenerationContext(options.moduleName, backendOptions)
        val protoFiles = backendOptions.protoSources.map { it.load() }

        return GeneratedProtocolPackage(
            language = language,
            files = protoFiles + listOf(
                GeneratedProtocolFile("proto/${context.optionsName}", generateNanopbOptions(context)),
                GeneratedProtocolFile("CMakeLists.txt", generateCMakeLists(context)),
                GeneratedProtocolFile(context.headerName, generateHeader(context)),
                GeneratedProtocolFile(context.sourceName, generateSource(context)),
                GeneratedProtocolFile("README.md", generateReadme(context, protoFiles)),
            ),
        )
    }

    private fun ProtocolGenerationOptions.cBackendOptions(): CBackendOptions = when (val backendOptions = backend) {
        is CBackendOptions -> backendOptions
        DefaultProtocolBackendOptions -> CBackendOptions()
        else -> error("C generator does not accept backend options: ${backendOptions::class.simpleName}")
    }

    private fun DeviceSpec<*>.cGenerationContext(moduleName: String, options: CBackendOptions): CContext {
        val cModuleName = moduleName.toCIdentifier("device")
        val properties = toProtocolSchema().properties.map { property ->
            val cName = property.name.toCIdentifier("property")
            CPropertyInfo(
                name = property.name,
                cName = cName,
                enumSuffix = cName.uppercase(),
                type = property.type,
                readable = property.readable,
                writable = property.writable,
                rootStructName = when (property.type) {
                    is ProtocolPropertyType.Scalar -> null
                    is ProtocolPropertyType.StructuredMeta -> "${cModuleName}_${cName}_t"
                },
            )
        }
        return CContext(
            moduleName = cModuleName,
            includeGuard = "${cModuleName.uppercase()}_PROTOCOL_H",
            headerName = "${cModuleName}_protocol.h",
            sourceName = "${cModuleName}_protocol.c",
            optionsName = "meta.options",
            textMaxLength = options.nanopbTextMaxLength,
            properties = properties,
        )
    }

    private fun generateNanopbOptions(context: CContext): String = """
# Generated by controls-proto. Used by nanopb generator.
#
# Keep recursive ProtoMeta.items as callbacks. This avoids impossible recursive
# by-value C structs and lets protocol code decode only requested fields.
*.ProtoMeta.items type:FT_CALLBACK

# Generated C code expects fixed C strings for map keys and string values.
*.ProtoMeta.ItemsEntry.key max_length:${context.textMaxLength}
*.ProtoMeta.ProtoValue.stringValue max_length:${context.textMaxLength}

# The device protocol currently uses only envelope.meta. Payload bytes and list
# value variants are ignored by the generated MCU handler.
*.ProtoEnvelope.dataBytes type:FT_IGNORE
*.ProtoMeta.ProtoValue.bytesValue type:FT_IGNORE
*.ProtoMeta.ProtoValue.listValue type:FT_IGNORE
*.ProtoMeta.ProtoValue.float64ListValue type:FT_IGNORE
""".trimIndent() + "\n"

    private fun generateCMakeLists(context: CContext): String = """
cmake_minimum_required(VERSION 3.16)

project(${context.moduleName}_protocol C)

set(${context.upperName}_PROTOCOL_CPM_VERSION "0.40.8" CACHE STRING "CPM.cmake version")
set(${context.upperName}_PROTOCOL_NANOPB_GIT_TAG "master" CACHE STRING "nanopb git tag or branch")

set(CPM_DOWNLOAD_LOCATION "${'$'}{CMAKE_CURRENT_BINARY_DIR}/cmake/CPM_${'$'}{${context.upperName}_PROTOCOL_CPM_VERSION}.cmake")
if(NOT EXISTS "${'$'}{CPM_DOWNLOAD_LOCATION}")
    file(DOWNLOAD
        "https://github.com/cpm-cmake/CPM.cmake/releases/download/v${'$'}{${context.upperName}_PROTOCOL_CPM_VERSION}/CPM.cmake"
        "${'$'}{CPM_DOWNLOAD_LOCATION}"
        TLS_VERIFY ON
    )
endif()
include("${'$'}{CPM_DOWNLOAD_LOCATION}")

CPMAddPackage(
    NAME lib_nanopb
    GITHUB_REPOSITORY nanopb/nanopb
    GIT_TAG ${'$'}{${context.upperName}_PROTOCOL_NANOPB_GIT_TAG}
    DOWNLOAD_ONLY YES
)

if(CPM_lib_nanopb_SOURCE)
    set(NANOPB_SRC_ROOT_FOLDER "${'$'}{CPM_lib_nanopb_SOURCE}" CACHE PATH "Path to nanopb source checkout" FORCE)
elseif(lib_nanopb_SOURCE_DIR)
    set(NANOPB_SRC_ROOT_FOLDER "${'$'}{lib_nanopb_SOURCE_DIR}" CACHE PATH "Path to nanopb source checkout" FORCE)
else()
    message(FATAL_ERROR "CPM did not provide nanopb source path")
endif()

list(APPEND CMAKE_MODULE_PATH "${'$'}{NANOPB_SRC_ROOT_FOLDER}/extra")
find_package(Nanopb REQUIRED)

set(NANOPB_DEPENDS "${'$'}{CMAKE_CURRENT_SOURCE_DIR}/proto/${context.optionsName}")
NANOPB_GENERATE_CPP(TARGET ${context.moduleName}_meta_proto "${'$'}{CMAKE_CURRENT_SOURCE_DIR}/proto/meta.proto")

add_library(${context.moduleName}_protocol STATIC
    ${context.sourceName}
)

target_compile_features(${context.moduleName}_protocol PUBLIC c_std_99)
target_compile_options(${context.moduleName}_protocol
    PRIVATE
        ${'$'}<$<C_COMPILER_ID:Clang,GNU>:-Wno-unused-function>
        ${'$'}<$<C_COMPILER_ID:Clang,GNU>:-Wno-unused-variable>
)
target_include_directories(${context.moduleName}_protocol
    PUBLIC
        "${'$'}{CMAKE_CURRENT_SOURCE_DIR}"
        "${'$'}{CMAKE_CURRENT_BINARY_DIR}"
)
target_link_libraries(${context.moduleName}_protocol
    PUBLIC
        ${context.moduleName}_meta_proto
)

install(TARGETS ${context.moduleName}_protocol ARCHIVE DESTINATION lib)
install(FILES
    "${'$'}{CMAKE_CURRENT_SOURCE_DIR}/${context.headerName}"
    "${'$'}{CMAKE_CURRENT_BINARY_DIR}/meta.pb.h"
    DESTINATION include
)
""".trimIndent() + "\n"

    private fun generateHeader(context: CContext): String = buildString {
        appendLine("/* Generated by controls-proto. Do not edit by hand. */")
        appendLine("#ifndef ${context.includeGuard}")
        appendLine("#define ${context.includeGuard}")
        appendLine()
        appendLine("#include <stdbool.h>")
        appendLine("#include <stddef.h>")
        appendLine("#include <stdint.h>")
        appendLine()
        appendLine("#ifdef __cplusplus")
        appendLine("extern \"C\" {")
        appendLine("#endif")
        appendLine()
        appendErrorCodes(context)
        appendLine("typedef struct ${context.moduleName}_string {")
        appendLine("    const char *data;")
        appendLine("    size_t size;")
        appendLine("} ${context.moduleName}_string_t;")
        appendLine()
        context.properties.forEach { property ->
            val model = property.type as? ProtocolPropertyType.StructuredMeta ?: return@forEach
            appendStructuredStructs(context, model.model.rootNode, listOf(model.model.rootNode.name))
        }
        appendRequestTypes(context)
        appendResponseTypes(context)
        appendLine("typedef ${context.moduleName}_response_t (*${context.moduleName}_request_handler_t)(")
        appendLine("    const ${context.moduleName}_request_t *request,")
        appendLine("    void *user_data")
        appendLine(");")
        appendLine()
        appendLine("int ${context.moduleName}_handle_message(")
        appendLine("    const uint8_t *input,")
        appendLine("    size_t input_size,")
        appendLine("    uint8_t *output,")
        appendLine("    size_t output_capacity,")
        appendLine("    ${context.moduleName}_request_handler_t handler,")
        appendLine("    void *user_data")
        appendLine(");")
        appendLine()
        appendResponseConstructors(context)
        appendLine("#ifdef __cplusplus")
        appendLine("}")
        appendLine("#endif")
        appendLine()
        appendLine("#endif")
    }

    private fun StringBuilder.appendErrorCodes(context: CContext) {
        appendLine("#define ${context.upperName}_PROTOCOL_NO_RESPONSE 0")
        appendLine("#define ${context.upperName}_PROTOCOL_ERROR_DECODE_REQUEST -1")
        appendLine("#define ${context.upperName}_PROTOCOL_ERROR_MISSING_METHOD -2")
        appendLine("#define ${context.upperName}_PROTOCOL_ERROR_MISSING_METHOD_VALUE -3")
        appendLine("#define ${context.upperName}_PROTOCOL_ERROR_INVALID_METHOD_TYPE -4")
        appendLine("#define ${context.upperName}_PROTOCOL_ERROR_UNKNOWN_METHOD -5")
        appendLine("#define ${context.upperName}_PROTOCOL_ERROR_INVALID_REQUEST -6")
        appendLine("#define ${context.upperName}_PROTOCOL_ERROR_INVALID_PROPERTY_VALUE -7")
        appendLine("#define ${context.upperName}_PROTOCOL_ERROR_RESPONSE_MISMATCH -8")
        appendLine("#define ${context.upperName}_PROTOCOL_ERROR_OUTPUT_BUFFER_TOO_SMALL -9")
        appendLine("#define ${context.upperName}_PROTOCOL_ERROR_ENCODE_RESPONSE -10")
        appendLine()
    }

    private fun StringBuilder.appendStructuredStructs(context: CContext, node: ProtocolMetaNode, path: List<String>) {
        node.children.filter { it.children.isNotEmpty() }.forEach { child ->
            appendStructuredStructs(context, child, path + child.name)
        }

        val structName = context.structName(path)
        appendLine("typedef struct $structName {")
        node.children.forEach { child ->
            val type = if (child.children.isEmpty()) {
                requireNotNull(child.scalar).cType(context)
            } else {
                "${context.structName(path + child.name)}_t"
            }
            appendLine("    $type ${child.name.toCIdentifier("field")};")
        }
        appendLine("} ${structName}_t;")
        appendLine()
    }

    private fun StringBuilder.appendRequestTypes(context: CContext) {
        appendLine("typedef enum ${context.moduleName}_request_kind {")
        context.readableProperties.forEach { appendLine("    ${context.upperName}_REQUEST_GET_${it.enumSuffix},") }
        context.writableProperties.forEach { appendLine("    ${context.upperName}_REQUEST_SET_${it.enumSuffix},") }
        appendLine("} ${context.moduleName}_request_kind_t;")
        appendLine()
        appendLine("typedef struct ${context.moduleName}_request {")
        appendLine("    ${context.moduleName}_request_kind_t kind;")
        appendLine("    union {")
        context.writableProperties.forEach { appendLine("        ${it.valueCType(context)} ${it.unionFieldName};") }
        appendLine("    } value;")
        appendLine("} ${context.moduleName}_request_t;")
        appendLine()
    }

    private fun StringBuilder.appendResponseTypes(context: CContext) {
        appendLine("typedef enum ${context.moduleName}_response_kind {")
        appendLine("    ${context.upperName}_RESPONSE_NONE = 0,")
        context.properties.forEach { appendLine("    ${context.upperName}_RESPONSE_${it.enumSuffix},") }
        appendLine("} ${context.moduleName}_response_kind_t;")
        appendLine()
        appendLine("typedef struct ${context.moduleName}_response {")
        appendLine("    ${context.moduleName}_response_kind_t kind;")
        appendLine("    union {")
        context.properties.forEach { appendLine("        ${it.valueCType(context)} ${it.unionFieldName};") }
        appendLine("    } value;")
        appendLine("} ${context.moduleName}_response_t;")
        appendLine()
    }

    private fun StringBuilder.appendResponseConstructors(context: CContext) {
        appendLine("static inline ${context.moduleName}_response_t ${context.moduleName}_no_response(void) {")
        appendLine("    ${context.moduleName}_response_t response;")
        appendLine("    response.kind = ${context.upperName}_RESPONSE_NONE;")
        appendLine("    return response;")
        appendLine("}")
        appendLine()
        context.properties.forEach { property ->
            appendLine("static inline ${context.moduleName}_response_t ${context.moduleName}_response_${property.cName}(${property.valueCType(context)} value) {")
            appendLine("    ${context.moduleName}_response_t response;")
            appendLine("    response.kind = ${context.upperName}_RESPONSE_${property.enumSuffix};")
            appendLine("    response.value.${property.unionFieldName} = value;")
            appendLine("    return response;")
            appendLine("}")
            appendLine()
        }
    }

    private fun generateSource(context: CContext): String = buildString {
        appendLine("/* Generated by controls-proto. Do not edit by hand. */")
        appendLine("#include \"${context.headerName}\"")
        appendLine()
        appendLine("#include \"pb_decode.h\"")
        appendLine("#include \"pb_encode.h\"")
        appendLine("#include \"meta.pb.h\"")
        appendLine()
        appendLine("#include <string.h>")
        appendLine()
        appendNanopbAliases(context)
        appendDecodeHelpers(context)
        appendScalarEncoders(context)
        appendEncodeNodeItem(context)
        appendStructuredDecoders(context)
        appendStructuredEncoders(context)
        appendRootDecode(context)
        appendRootEncode(context)
        appendHandleMessage(context)
    }

    private fun StringBuilder.appendNanopbAliases(context: CContext) {
        val packagePrefix = "space_kscience_dataforge_io_proto"
        appendLine("#ifndef ${context.upperName}_PROTO_ENVELOPE")
        appendLine("#define ${context.upperName}_PROTO_ENVELOPE ${packagePrefix}_ProtoEnvelope")
        appendLine("#endif")
        appendLine("#ifndef ${context.upperName}_PROTO_ENVELOPE_FIELDS")
        appendLine("#define ${context.upperName}_PROTO_ENVELOPE_FIELDS ${packagePrefix}_ProtoEnvelope_fields")
        appendLine("#endif")
        appendLine("#ifndef ${context.upperName}_PROTO_ENVELOPE_INIT_ZERO")
        appendLine("#define ${context.upperName}_PROTO_ENVELOPE_INIT_ZERO ${packagePrefix}_ProtoEnvelope_init_zero")
        appendLine("#endif")
        appendLine("#ifndef ${context.upperName}_PROTO_META_ITEMS_ENTRY")
        appendLine("#define ${context.upperName}_PROTO_META_ITEMS_ENTRY ${packagePrefix}_ProtoMeta_ItemsEntry")
        appendLine("#endif")
        appendLine("#ifndef ${context.upperName}_PROTO_META_ITEMS_ENTRY_FIELDS")
        appendLine("#define ${context.upperName}_PROTO_META_ITEMS_ENTRY_FIELDS ${packagePrefix}_ProtoMeta_ItemsEntry_fields")
        appendLine("#endif")
        appendLine("#ifndef ${context.upperName}_PROTO_META_ITEMS_ENTRY_INIT_ZERO")
        appendLine("#define ${context.upperName}_PROTO_META_ITEMS_ENTRY_INIT_ZERO ${packagePrefix}_ProtoMeta_ItemsEntry_init_zero")
        appendLine("#endif")
        appendLine("#ifndef ${context.upperName}_PROTO_VALUE_STRING_TAG")
        appendLine("#define ${context.upperName}_PROTO_VALUE_STRING_TAG ${packagePrefix}_ProtoMeta_ProtoValue_stringValue_tag")
        appendLine("#endif")
        appendLine("#ifndef ${context.upperName}_PROTO_VALUE_BOOL_TAG")
        appendLine("#define ${context.upperName}_PROTO_VALUE_BOOL_TAG ${packagePrefix}_ProtoMeta_ProtoValue_booleanValue_tag")
        appendLine("#endif")
        appendLine("#ifndef ${context.upperName}_PROTO_VALUE_DOUBLE_TAG")
        appendLine("#define ${context.upperName}_PROTO_VALUE_DOUBLE_TAG ${packagePrefix}_ProtoMeta_ProtoValue_doubleValue_tag")
        appendLine("#endif")
        appendLine("#ifndef ${context.upperName}_PROTO_VALUE_FLOAT_TAG")
        appendLine("#define ${context.upperName}_PROTO_VALUE_FLOAT_TAG ${packagePrefix}_ProtoMeta_ProtoValue_floatValue_tag")
        appendLine("#endif")
        appendLine("#ifndef ${context.upperName}_PROTO_VALUE_I32_TAG")
        appendLine("#define ${context.upperName}_PROTO_VALUE_I32_TAG ${packagePrefix}_ProtoMeta_ProtoValue_int32Value_tag")
        appendLine("#endif")
        appendLine("#ifndef ${context.upperName}_PROTO_VALUE_I64_TAG")
        appendLine("#define ${context.upperName}_PROTO_VALUE_I64_TAG ${packagePrefix}_ProtoMeta_ProtoValue_int64Value_tag")
        appendLine("#endif")
        appendLine()
    }

    private fun StringBuilder.appendDecodeHelpers(context: CContext) {
        appendLine("static bool ${context.moduleName}_copy_c_string(char *target, size_t target_size, const char *source) {")
        appendLine("    size_t source_size = strlen(source);")
        appendLine("    if (source_size + 1u > target_size) return false;")
        appendLine("    memcpy(target, source, source_size + 1u);")
        appendLine("    return true;")
        appendLine("}")
        appendLine()
        appendLine("static bool ${context.moduleName}_copy_string_value(char *target, size_t target_size, ${context.moduleName}_string_t source) {")
        appendLine("    if (source.size + 1u > target_size) return false;")
        appendLine("    memcpy(target, source.data, source.size);")
        appendLine("    target[source.size] = '\\0';")
        appendLine("    return true;")
        appendLine("}")
        appendLine()
        appendLine("static bool ${context.moduleName}_is_key(const char *key, const char *expected) {")
        appendLine("    return strcmp(key, expected) == 0;")
        appendLine("}")
        appendLine()
        appendLine("static bool ${context.moduleName}_get_string_value(const ${context.upperName}_PROTO_META_ITEMS_ENTRY *entry, ${context.moduleName}_string_t *value) {")
        appendLine("    if (!entry->value.has_protoValue) return false;")
        appendLine("    if (entry->value.protoValue.which_value != ${context.upperName}_PROTO_VALUE_STRING_TAG) return false;")
        appendLine("    value->data = entry->value.protoValue.value.stringValue;")
        appendLine("    value->size = strlen(entry->value.protoValue.value.stringValue);")
        appendLine("    return true;")
        appendLine("}")
        appendLine()
        ProtocolScalar.values().filter { it != ProtocolScalar.STRING }.forEach { scalar ->
            appendLine("static bool ${context.moduleName}_get_${scalar.cSuffix()}_value(const ${context.upperName}_PROTO_META_ITEMS_ENTRY *entry, ${scalar.cType(context)} *value) {")
            appendLine("    if (!entry->value.has_protoValue) return false;")
            appendLine("    if (entry->value.protoValue.which_value != ${context.upperName}_PROTO_VALUE_${scalar.tagSuffix()}_TAG) return false;")
            appendLine("    *value = entry->value.protoValue.value.${scalar.protoValueField()};")
            appendLine("    return true;")
            appendLine("}")
            appendLine()
        }
    }

    private fun StringBuilder.appendStructuredDecoders(context: CContext) {
        context.properties.forEach { property ->
            val model = property.type as? ProtocolPropertyType.StructuredMeta ?: return@forEach
            appendStructuredDecodeDeclarations(context, model.model.rootNode, listOf(model.model.rootNode.name))
            appendLine()
            appendStructuredDecodeFunctions(context, model.model.rootNode, listOf(model.model.rootNode.name))
        }
    }

    private fun StringBuilder.appendStructuredDecodeDeclarations(context: CContext, node: ProtocolMetaNode, path: List<String>) {
        appendLine("static bool ${context.decodeCallbackName(path)}(pb_istream_t *stream, const pb_field_t *field, void **arg);")
        node.children.filter { it.children.isNotEmpty() }.forEach { child ->
            appendStructuredDecodeDeclarations(context, child, path + child.name)
        }
    }

    private fun StringBuilder.appendStructuredDecodeFunctions(context: CContext, node: ProtocolMetaNode, path: List<String>) {
        node.children.filter { it.children.isNotEmpty() }.forEach { child ->
            appendStructuredDecodeFunctions(context, child, path + child.name)
        }
        val typeName = "${context.structName(path)}_t"
        appendLine("typedef struct ${context.decodeContextName(path)} {")
        appendLine("    $typeName *out;")
        appendLine("} ${context.decodeContextName(path)}_t;")
        appendLine()
        appendLine("typedef struct ${context.decodeChildContextName(path)} {")
        appendLine("    $typeName *out;")
        appendLine("    const char *key;")
        appendLine("} ${context.decodeChildContextName(path)}_t;")
        appendLine()
        appendLine("static bool ${context.decodeChildCallbackName(path)}(pb_istream_t *stream, const pb_field_t *field, void **arg) {")
        appendLine("    ${context.decodeChildContextName(path)}_t *ctx = (${context.decodeChildContextName(path)}_t *)(*arg);")
        appendLine("    (void)ctx;")
        node.children.filter { it.children.isNotEmpty() }.forEach { child ->
            appendLine("    if (${context.moduleName}_is_key(ctx->key, \"${child.name}\")) {")
            appendLine("        ${context.decodeContextName(path + child.name)}_t child_ctx = { &ctx->out->${child.name.toCIdentifier("field")} };")
            appendLine("        void *child_arg = &child_ctx;")
            appendLine("        return ${context.decodeCallbackName(path + child.name)}(stream, field, &child_arg);")
            appendLine("    }")
        }
        appendLine("    (void)stream;")
        appendLine("    (void)field;")
        appendLine("    return true;")
        appendLine("}")
        appendLine()
        appendLine("static bool ${context.decodeCallbackName(path)}(pb_istream_t *stream, const pb_field_t *field, void **arg) {")
        appendLine("    (void)field;")
        appendLine("    ${context.decodeContextName(path)}_t *ctx = (${context.decodeContextName(path)}_t *)(*arg);")
        appendLine("    ${context.upperName}_PROTO_META_ITEMS_ENTRY entry = ${context.upperName}_PROTO_META_ITEMS_ENTRY_INIT_ZERO;")
        appendLine("    ${context.decodeChildContextName(path)}_t child_ctx = { ctx->out, entry.key };")
        appendLine("    entry.value.items.funcs.decode = ${context.decodeChildCallbackName(path)};")
        appendLine("    entry.value.items.arg = &child_ctx;")
        appendLine("    if (!pb_decode(stream, ${context.upperName}_PROTO_META_ITEMS_ENTRY_FIELDS, &entry)) return false;")
        node.children.forEach { child ->
            val fieldName = child.name.toCIdentifier("field")
            appendLine("    if (${context.moduleName}_is_key(entry.key, \"${child.name}\")) {")
            if (child.children.isEmpty()) {
                val scalar = requireNotNull(child.scalar)
                if (scalar == ProtocolScalar.STRING) {
                    appendLine("        ${context.moduleName}_string_t string_value;")
                    appendLine("        if (!${context.moduleName}_get_string_value(&entry, &string_value)) return false;")
                    appendLine("        ctx->out->$fieldName = string_value;")
                    appendLine("        return true;")
                } else {
                    appendLine("        return ${context.moduleName}_get_${scalar.cSuffix()}_value(&entry, &ctx->out->$fieldName);")
                }
            } else {
                appendLine("        return true;")
            }
            appendLine("    }")
        }
        appendLine("    return true;")
        appendLine("}")
        appendLine()
    }

    private fun StringBuilder.appendStructuredEncoders(context: CContext) {
        context.properties.forEach { property ->
            val model = property.type as? ProtocolPropertyType.StructuredMeta ?: return@forEach
            appendStructuredEncodeDeclarations(context, model.model.rootNode, listOf(model.model.rootNode.name))
            appendLine()
            appendStructuredEncodeFunctions(context, model.model.rootNode, listOf(model.model.rootNode.name))
        }
    }

    private fun StringBuilder.appendStructuredEncodeDeclarations(context: CContext, node: ProtocolMetaNode, path: List<String>) {
        appendLine("static bool ${context.encodeCallbackName(path)}(pb_ostream_t *stream, const pb_field_t *field, void * const *arg);")
        node.children.filter { it.children.isNotEmpty() }.forEach { child ->
            appendStructuredEncodeDeclarations(context, child, path + child.name)
        }
    }

    private fun StringBuilder.appendStructuredEncodeFunctions(context: CContext, node: ProtocolMetaNode, path: List<String>) {
        node.children.filter { it.children.isNotEmpty() }.forEach { child ->
            appendStructuredEncodeFunctions(context, child, path + child.name)
        }
        val typeName = "${context.structName(path)}_t"
        appendLine("static bool ${context.encodeCallbackName(path)}(pb_ostream_t *stream, const pb_field_t *field, void * const *arg) {")
        appendLine("    const $typeName *value = (const $typeName *)(*arg);")
        node.children.forEach { child ->
            val fieldName = child.name.toCIdentifier("field")
            if (child.children.isEmpty()) {
                appendLine("    if (!${context.encodeScalarItemName(requireNotNull(child.scalar))}(stream, field, \"${child.name}\", value->$fieldName)) return false;")
            } else {
                appendLine("    if (!${context.moduleName}_encode_node_item(stream, field, \"${child.name}\", ${context.encodeCallbackName(path + child.name)}, &value->$fieldName)) return false;")
            }
        }
        appendLine("    return true;")
        appendLine("}")
        appendLine()
    }

    private fun StringBuilder.appendRootDecode(context: CContext) {
        appendLine("typedef enum ${context.moduleName}_method {")
        appendLine("    ${context.upperName}_METHOD_NONE,")
        appendLine("    ${context.upperName}_METHOD_GET,")
        appendLine("    ${context.upperName}_METHOD_POST,")
        appendLine("    ${context.upperName}_METHOD_INVALID,")
        appendLine("} ${context.moduleName}_method_t;")
        appendLine()
        appendLine("typedef struct ${context.moduleName}_decode_context {")
        appendLine("    ${context.moduleName}_request_t request;")
        appendLine("    ${context.moduleName}_method_t method;")
        context.properties.forEach {
            appendLine("    bool ${it.hasFlagName};")
            appendLine("    bool ${it.validFlagName};")
        }
        appendLine("} ${context.moduleName}_decode_context_t;")
        appendLine()
        appendRootNestedDecode(context)
        appendLine("static bool ${context.moduleName}_decode_root_item(pb_istream_t *stream, const pb_field_t *field, void **arg) {")
        appendLine("    (void)field;")
        appendLine("    ${context.moduleName}_decode_context_t *ctx = (${context.moduleName}_decode_context_t *)(*arg);")
        appendLine("    ${context.upperName}_PROTO_META_ITEMS_ENTRY entry = ${context.upperName}_PROTO_META_ITEMS_ENTRY_INIT_ZERO;")
        appendLine("    ${context.moduleName}_root_child_decode_context_t child_ctx = { ctx, entry.key };")
        appendLine("    entry.value.items.funcs.decode = ${context.moduleName}_decode_root_child_item;")
        appendLine("    entry.value.items.arg = &child_ctx;")
        appendLine("    if (!pb_decode(stream, ${context.upperName}_PROTO_META_ITEMS_ENTRY_FIELDS, &entry)) return false;")
        appendLine("    if (${context.moduleName}_is_key(entry.key, \"$METHOD_FIELD\")) {")
        appendLine("        ${context.moduleName}_string_t method;")
        appendLine("        if (!${context.moduleName}_get_string_value(&entry, &method)) {")
        appendLine("            ctx->method = ${context.upperName}_METHOD_INVALID;")
        appendLine("            return true;")
        appendLine("        }")
        appendLine("        if (method.size == 3u && memcmp(method.data, \"$GET_METHOD\", 3u) == 0) ctx->method = ${context.upperName}_METHOD_GET;")
        appendLine("        else if (method.size == 4u && memcmp(method.data, \"$POST_METHOD\", 4u) == 0) ctx->method = ${context.upperName}_METHOD_POST;")
        appendLine("        else ctx->method = ${context.upperName}_METHOD_INVALID;")
        appendLine("        return true;")
        appendLine("    }")
        context.properties.forEach { property ->
            appendLine("    if (${context.moduleName}_is_key(entry.key, \"${property.name}\")) {")
            appendLine("        ctx->${property.hasFlagName} = true;")
            when (val type = property.type) {
                is ProtocolPropertyType.Scalar -> {
                    if (property.writable) {
                        if (type.scalar == ProtocolScalar.STRING) {
                            appendLine("        /* String scalar POST values are exposed as borrowed data from the decoded packet. */")
                            appendLine("        ctx->${property.validFlagName} = ${context.moduleName}_get_string_value(&entry, &ctx->request.value.${property.unionFieldName});")
                        } else {
                            appendLine("        ctx->${property.validFlagName} = ${context.moduleName}_get_${type.scalar.cSuffix()}_value(&entry, &ctx->request.value.${property.unionFieldName});")
                        }
                    } else {
                        appendLine("        ctx->${property.validFlagName} = true;")
                    }
                }
                is ProtocolPropertyType.StructuredMeta -> {
                    appendLine("        ctx->${property.validFlagName} = true;")
                }
            }
            appendLine("        return true;")
            appendLine("    }")
        }
        appendLine("    return true;")
        appendLine("}")
        appendLine()
        appendLine("static int ${context.moduleName}_decode_host_request(const uint8_t *input, size_t input_size, ${context.moduleName}_request_t *request) {")
        appendLine("    ${context.upperName}_PROTO_ENVELOPE envelope = ${context.upperName}_PROTO_ENVELOPE_INIT_ZERO;")
        appendLine("    ${context.moduleName}_decode_context_t ctx;")
        appendLine("    memset(&ctx, 0, sizeof(ctx));")
        appendLine("    envelope.meta.items.funcs.decode = ${context.moduleName}_decode_root_item;")
        appendLine("    envelope.meta.items.arg = &ctx;")
        appendLine("    pb_istream_t stream = pb_istream_from_buffer(input, input_size);")
        appendLine("    if (!pb_decode(&stream, ${context.upperName}_PROTO_ENVELOPE_FIELDS, &envelope)) return ${context.upperName}_PROTOCOL_ERROR_DECODE_REQUEST;")
        appendLine("    if (!envelope.has_meta) return ${context.upperName}_PROTOCOL_ERROR_DECODE_REQUEST;")
        appendLine("    if (ctx.method == ${context.upperName}_METHOD_NONE) return ${context.upperName}_PROTOCOL_ERROR_MISSING_METHOD;")
        appendLine("    if (ctx.method == ${context.upperName}_METHOD_INVALID) return ${context.upperName}_PROTOCOL_ERROR_UNKNOWN_METHOD;")
        appendLine("    if (ctx.method == ${context.upperName}_METHOD_GET) {")
        context.readableProperties.forEach {
            appendLine("        if (ctx.${it.hasFlagName}) { request->kind = ${context.upperName}_REQUEST_GET_${it.enumSuffix}; *request = ctx.request; request->kind = ${context.upperName}_REQUEST_GET_${it.enumSuffix}; return 1; }")
        }
        appendLine("        return ${context.upperName}_PROTOCOL_ERROR_INVALID_REQUEST;")
        appendLine("    }")
        appendLine("    if (ctx.method == ${context.upperName}_METHOD_POST) {")
        context.writableProperties.forEach {
            appendLine("        if (ctx.${it.hasFlagName}) {")
            appendLine("            if (!ctx.${it.validFlagName}) return ${context.upperName}_PROTOCOL_ERROR_INVALID_PROPERTY_VALUE;")
            appendLine("            *request = ctx.request;")
            appendLine("            request->kind = ${context.upperName}_REQUEST_SET_${it.enumSuffix};")
            appendLine("            return 1;")
            appendLine("        }")
        }
        appendLine("        return ${context.upperName}_PROTOCOL_ERROR_INVALID_REQUEST;")
        appendLine("    }")
        appendLine("    return ${context.upperName}_PROTOCOL_ERROR_UNKNOWN_METHOD;")
        appendLine("}")
        appendLine()
    }

    private fun StringBuilder.appendRootNestedDecode(context: CContext) {
        appendLine("typedef struct ${context.moduleName}_root_child_decode_context {")
        appendLine("    ${context.moduleName}_decode_context_t *root;")
        appendLine("    const char *key;")
        appendLine("} ${context.moduleName}_root_child_decode_context_t;")
        appendLine()
        appendLine("static bool ${context.moduleName}_decode_root_child_item(pb_istream_t *stream, const pb_field_t *field, void **arg) {")
        appendLine("    ${context.moduleName}_root_child_decode_context_t *ctx = (${context.moduleName}_root_child_decode_context_t *)(*arg);")
        context.properties.forEach { property ->
            val model = property.type as? ProtocolPropertyType.StructuredMeta ?: return@forEach
            appendLine("    if (${context.moduleName}_is_key(ctx->key, \"${property.name}\")) {")
            appendLine("        ${context.decodeContextName(listOf(model.model.rootNode.name))}_t child_ctx = { &ctx->root->request.value.${property.unionFieldName} };")
            appendLine("        void *child_arg = &child_ctx;")
            appendLine("        return ${context.decodeCallbackName(listOf(model.model.rootNode.name))}(stream, field, &child_arg);")
            appendLine("    }")
        }
        appendLine("    (void)stream;")
        appendLine("    (void)field;")
        appendLine("    return true;")
        appendLine("}")
        appendLine()
    }

    private fun StringBuilder.appendRootEncode(context: CContext) {
        appendLine("typedef struct ${context.moduleName}_encode_context {")
        appendLine("    const char *method;")
        appendLine("    const ${context.moduleName}_response_t *response;")
        appendLine("} ${context.moduleName}_encode_context_t;")
        appendLine()
        appendLine("static bool ${context.moduleName}_encode_root_items(pb_ostream_t *stream, const pb_field_t *field, void * const *arg) {")
        appendLine("    const ${context.moduleName}_encode_context_t *ctx = (const ${context.moduleName}_encode_context_t *)(*arg);")
        appendLine("    if (!${context.moduleName}_encode_cstr_item(stream, field, \"$METHOD_FIELD\", ctx->method)) return false;")
        appendLine("    switch (ctx->response->kind) {")
        context.properties.forEach { property ->
            appendLine("    case ${context.upperName}_RESPONSE_${property.enumSuffix}:")
            when (val type = property.type) {
                is ProtocolPropertyType.Scalar -> {
                    appendLine("        return ${context.encodeScalarItemName(type.scalar)}(stream, field, \"${property.name}\", ctx->response->value.${property.unionFieldName});")
                }
                is ProtocolPropertyType.StructuredMeta -> {
                    appendLine("        return ${context.moduleName}_encode_node_item(stream, field, \"${property.name}\", ${context.encodeCallbackName(listOf(type.model.rootNode.name))}, &ctx->response->value.${property.unionFieldName});")
                }
            }
        }
        appendLine("    default:")
        appendLine("        return false;")
        appendLine("    }")
        appendLine("}")
        appendLine()
        appendLine("static int ${context.moduleName}_write_response_message(const char *method, const ${context.moduleName}_response_t *response, uint8_t *output, size_t output_capacity) {")
        appendLine("    ${context.upperName}_PROTO_ENVELOPE envelope = ${context.upperName}_PROTO_ENVELOPE_INIT_ZERO;")
        appendLine("    ${context.moduleName}_encode_context_t ctx = { method, response };")
        appendLine("    envelope.has_meta = true;")
        appendLine("    envelope.meta.items.funcs.encode = ${context.moduleName}_encode_root_items;")
        appendLine("    envelope.meta.items.arg = &ctx;")
        appendLine("    pb_ostream_t stream = pb_ostream_from_buffer(output, output_capacity);")
        appendLine("    if (!pb_encode(&stream, ${context.upperName}_PROTO_ENVELOPE_FIELDS, &envelope)) return ${context.upperName}_PROTOCOL_ERROR_ENCODE_RESPONSE;")
        appendLine("    return (int)stream.bytes_written;")
        appendLine("}")
        appendLine()
        appendLine("static int ${context.moduleName}_encode_host_response(const ${context.moduleName}_request_t *request, const ${context.moduleName}_response_t *response, uint8_t *output, size_t output_capacity) {")
        appendLine("    (void)output_capacity;")
        appendLine("    switch (request->kind) {")
        context.readableProperties.forEach {
            appendLine("    case ${context.upperName}_REQUEST_GET_${it.enumSuffix}:")
            appendLine("        if (response->kind != ${context.upperName}_RESPONSE_${it.enumSuffix}) return ${context.upperName}_PROTOCOL_ERROR_RESPONSE_MISMATCH;")
            appendLine("        return ${context.moduleName}_write_response_message(\"$GET_METHOD\", response, output, output_capacity);")
        }
        context.writableProperties.forEach {
            appendLine("    case ${context.upperName}_REQUEST_SET_${it.enumSuffix}:")
            appendLine("        if (response->kind != ${context.upperName}_RESPONSE_${it.enumSuffix}) return ${context.upperName}_PROTOCOL_ERROR_RESPONSE_MISMATCH;")
            appendLine("        return ${context.moduleName}_write_response_message(\"$POST_METHOD\", response, output, output_capacity);")
        }
        appendLine("    default:")
        appendLine("        return ${context.upperName}_PROTOCOL_ERROR_RESPONSE_MISMATCH;")
        appendLine("    }")
        appendLine("}")
        appendLine()
    }

    private fun StringBuilder.appendEncodeNodeItem(context: CContext) {
        appendLine("static bool ${context.moduleName}_encode_node_item(")
        appendLine("    pb_ostream_t *stream,")
        appendLine("    const pb_field_t *field,")
        appendLine("    const char *key,")
        appendLine("    bool (*items_encoder)(pb_ostream_t *, const pb_field_t *, void * const *),")
        appendLine("    const void *value")
        appendLine(") {")
        appendLine("    ${context.upperName}_PROTO_META_ITEMS_ENTRY entry = ${context.upperName}_PROTO_META_ITEMS_ENTRY_INIT_ZERO;")
        appendLine("    if (!${context.moduleName}_copy_c_string(entry.key, sizeof(entry.key), key)) return false;")
        appendLine("    entry.has_value = true;")
        appendLine("    entry.value.items.funcs.encode = items_encoder;")
        appendLine("    entry.value.items.arg = (void *)value;")
        appendLine("    return pb_encode_tag_for_field(stream, field) && pb_encode_submessage(stream, ${context.upperName}_PROTO_META_ITEMS_ENTRY_FIELDS, &entry);")
        appendLine("}")
        appendLine()
    }

    private fun StringBuilder.appendScalarEncoders(context: CContext) {
        appendLine("static bool ${context.moduleName}_encode_string_item(pb_ostream_t *stream, const pb_field_t *field, const char *key, ${context.moduleName}_string_t value) {")
        appendLine("    ${context.upperName}_PROTO_META_ITEMS_ENTRY entry = ${context.upperName}_PROTO_META_ITEMS_ENTRY_INIT_ZERO;")
        appendLine("    if (!${context.moduleName}_copy_c_string(entry.key, sizeof(entry.key), key)) return false;")
        appendLine("    entry.has_value = true;")
        appendLine("    entry.value.has_protoValue = true;")
        appendLine("    entry.value.protoValue.which_value = ${context.upperName}_PROTO_VALUE_STRING_TAG;")
        appendLine("    if (!${context.moduleName}_copy_string_value(entry.value.protoValue.value.stringValue, sizeof(entry.value.protoValue.value.stringValue), value)) return false;")
        appendLine("    return pb_encode_tag_for_field(stream, field) && pb_encode_submessage(stream, ${context.upperName}_PROTO_META_ITEMS_ENTRY_FIELDS, &entry);")
        appendLine("}")
        appendLine()
        appendLine("static bool ${context.moduleName}_encode_cstr_item(pb_ostream_t *stream, const pb_field_t *field, const char *key, const char *value) {")
        appendLine("    ${context.moduleName}_string_t string_value = { value, strlen(value) };")
        appendLine("    return ${context.moduleName}_encode_string_item(stream, field, key, string_value);")
        appendLine("}")
        appendLine()
        ProtocolScalar.values().filter { it != ProtocolScalar.STRING }.forEach { scalar ->
            appendLine("static bool ${context.encodeScalarItemName(scalar)}(pb_ostream_t *stream, const pb_field_t *field, const char *key, ${scalar.cType(context)} value) {")
            appendLine("    ${context.upperName}_PROTO_META_ITEMS_ENTRY entry = ${context.upperName}_PROTO_META_ITEMS_ENTRY_INIT_ZERO;")
            appendLine("    if (!${context.moduleName}_copy_c_string(entry.key, sizeof(entry.key), key)) return false;")
            appendLine("    entry.has_value = true;")
            appendLine("    entry.value.has_protoValue = true;")
            appendLine("    entry.value.protoValue.which_value = ${context.upperName}_PROTO_VALUE_${scalar.tagSuffix()}_TAG;")
            appendLine("    entry.value.protoValue.value.${scalar.protoValueField()} = value;")
            appendLine("    return pb_encode_tag_for_field(stream, field) && pb_encode_submessage(stream, ${context.upperName}_PROTO_META_ITEMS_ENTRY_FIELDS, &entry);")
            appendLine("}")
            appendLine()
        }
    }

    private fun StringBuilder.appendHandleMessage(context: CContext) {
        appendLine("int ${context.moduleName}_handle_message(")
        appendLine("    const uint8_t *input,")
        appendLine("    size_t input_size,")
        appendLine("    uint8_t *output,")
        appendLine("    size_t output_capacity,")
        appendLine("    ${context.moduleName}_request_handler_t handler,")
        appendLine("    void *user_data")
        appendLine(") {")
        appendLine("    if (input == NULL || output == NULL || handler == NULL) return ${context.upperName}_PROTOCOL_ERROR_DECODE_REQUEST;")
        appendLine("    ${context.moduleName}_request_t request;")
        appendLine("    int decode_status = ${context.moduleName}_decode_host_request(input, input_size, &request);")
        appendLine("    if (decode_status < 0) return decode_status;")
        appendLine("    ${context.moduleName}_response_t response = handler(&request, user_data);")
        appendLine("    if (response.kind == ${context.upperName}_RESPONSE_NONE) return ${context.upperName}_PROTOCOL_NO_RESPONSE;")
        appendLine("    return ${context.moduleName}_encode_host_response(&request, &response, output, output_capacity);")
        appendLine("}")
    }

    private fun generateReadme(context: CContext, protoFiles: List<GeneratedProtocolFile>): String {
        val installedProtoFiles = protoFiles.joinToString(separator = "\n") { "- `${it.relativePath}`" }
            .ifBlank { "- none" }
        return """
# ${context.moduleName}_protocol

Generated C protocol code for host-to-device messages.

Installed schema files:

$installedProtoFiles
- `proto/${context.optionsName}`
- `CMakeLists.txt`

## Dependencies

This C backend uses nanopb. The generated `CMakeLists.txt` resolves nanopb with CPM.cmake by default.
The nanopb repo contains the runtime files, generator, and CMake helper used here.

Example:

```sh
cmake -S . -B build
cmake --build build
```

If you already have a local nanopb checkout, pass it through CPM:

```sh
cmake -S . -B build -DCPM_lib_nanopb_SOURCE=/path/to/nanopb
cmake --build build
```

The generated protocol file includes:

```c
#include "pb_decode.h"
#include "pb_encode.h"
#include "meta.pb.h"
```

Public API:

```c
int ${context.moduleName}_handle_message(
    const uint8_t *input,
    size_t input_size,
    uint8_t *output,
    size_t output_capacity,
    ${context.moduleName}_request_handler_t handler,
    void *user_data
);
```

Return contract: `> 0` means response bytes written, `0` means no response, `< 0` is an error code.
""".trimIndent() + "\n"
    }

    private fun CContext.structName(path: List<String>): String = "${moduleName}_${path.pathIdentifier()}"
    private fun CContext.decodeContextName(path: List<String>): String = "${structName(path)}_decode_context"
    private fun CContext.decodeChildContextName(path: List<String>): String = "${structName(path)}_child_decode_context"
    private fun CContext.decodeCallbackName(path: List<String>): String = "${structName(path)}_decode_item"
    private fun CContext.decodeChildCallbackName(path: List<String>): String = "${structName(path)}_decode_child_item"
    private fun CContext.encodeCallbackName(path: List<String>): String = "${structName(path)}_encode_items"
    private fun CContext.encodeScalarItemName(scalar: ProtocolScalar): String = "${moduleName}_encode_${scalar.cSuffix()}_item"

    private fun CPropertyInfo.valueCType(context: CContext): String = when (val propertyType = type) {
        is ProtocolPropertyType.Scalar -> propertyType.scalar.cType(context)
        is ProtocolPropertyType.StructuredMeta -> requireNotNull(rootStructName)
    }

    private fun ProtocolScalar.cType(context: CContext): String = when (this) {
        ProtocolScalar.INT32 -> "int32_t"
        ProtocolScalar.INT64 -> "int64_t"
        ProtocolScalar.FLOAT32 -> "float"
        ProtocolScalar.FLOAT64 -> "double"
        ProtocolScalar.BOOLEAN -> "bool"
        ProtocolScalar.STRING -> "${context.moduleName}_string_t"
    }

    private fun ProtocolScalar.cSuffix(): String = when (this) {
        ProtocolScalar.INT32 -> "i32"
        ProtocolScalar.INT64 -> "i64"
        ProtocolScalar.FLOAT32 -> "float"
        ProtocolScalar.FLOAT64 -> "double"
        ProtocolScalar.BOOLEAN -> "bool"
        ProtocolScalar.STRING -> "string"
    }

    private fun ProtocolScalar.tagSuffix(): String = when (this) {
        ProtocolScalar.INT32 -> "I32"
        ProtocolScalar.INT64 -> "I64"
        ProtocolScalar.FLOAT32 -> "FLOAT"
        ProtocolScalar.FLOAT64 -> "DOUBLE"
        ProtocolScalar.BOOLEAN -> "BOOL"
        ProtocolScalar.STRING -> "STRING"
    }

    private fun ProtocolScalar.protoValueField(): String = when (this) {
        ProtocolScalar.INT32 -> "int32Value"
        ProtocolScalar.INT64 -> "int64Value"
        ProtocolScalar.FLOAT32 -> "floatValue"
        ProtocolScalar.FLOAT64 -> "doubleValue"
        ProtocolScalar.BOOLEAN -> "booleanValue"
        ProtocolScalar.STRING -> "stringValue"
    }

    private fun List<String>.pathIdentifier(): String =
        joinToString(separator = "_") { it.toCIdentifier("model") }

    private val cKeywords = setOf(
        "auto", "break", "case", "char", "const", "continue", "default", "do", "double", "else",
        "enum", "extern", "float", "for", "goto", "if", "inline", "int", "long", "register",
        "restrict", "return", "short", "signed", "sizeof", "static", "struct", "switch", "typedef",
        "union", "unsigned", "void", "volatile", "while", "_Bool",
    )

    private fun String.toCIdentifier(fallback: String): String {
        val identifier = toSnakeCase()
            .map { char -> if (char.isLetterOrDigit() || char == '_') char else '_' }
            .joinToString(separator = "")
            .trim('_')
            .ifBlank { fallback }
            .let { if (it.first().isDigit()) "_$it" else it }
        return if (identifier in cKeywords) "${identifier}_value" else identifier
    }

    private fun String.toSnakeCase(): String {
        if (isBlank()) return ""
        val builder = StringBuilder()
        forEachIndexed { index, char ->
            when {
                char.isUpperCase() -> {
                    if (index > 0 && builder.lastOrNull() != '_') builder.append('_')
                    builder.append(char.lowercaseChar())
                }
                char.isLetterOrDigit() -> builder.append(char.lowercaseChar())
                builder.lastOrNull() != '_' -> builder.append('_')
            }
        }
        return builder.toString().trim('_')
    }
}
